---
title: "Camparison of 401K VS Social Security for Retirement"
author: "Partha Banerjee, Rohan Fray, Vincent Ying"
date: "November 19, 2014"
output: html_document
---


  
# Library and Directory Config
```{r echo=FALSE}
# Add all required packages here. 
required.packages <- c("plyr", 
                       "ggplot2",
                       "gdata")

# Check to see if packages in required.packages are installed
have.pkgs <- required.packages %in% installed.packages()

if(length(required.packages) > sum(have.pkgs)){
  install.packages(required.packages[!have.pkgs])
}

for(pkg in required.packages){
  library(pkg, character.only = TRUE)
}

# Make sure we're in the right working directory:  "Code"
if("Code" %in% list.files()){
  setwd("Code")
}

if(!("Code" %in% list.files("..")))
{
  stop
}
```

# Load Data

```{r data}
# SSA Dataset (Taken from supplement13.xlsx)
ssa_taxrate = read.csv("../Data/OASDI - Table 2.A3 - Annual max taxable earnings and contribution rates.csv")
ssa_taxamt = read.csv("../Data/OASDI - Table 2.A4 - Maximum annual contribution.csv")
ssa_benefit = read.csv("../Data/OASDI - Table 6.B3 - All Benefit.csv")

# 401k Dataset
form5500 = read.csv("../Data/f_5500_2013_latest-min.csv")
form5500R = read.csv("../Data/F_SCH_R_PART1_2013_latest.csv")
```

# Clean Data

```{r}
if (FALSE) {
form5500 = read.csv("../Data/f_5500_2013_latest.csv")

# Features to Keep from 5500
keeps <- c(
"ACK_ID", 
"FORM_PLAN_YEAR_BEGIN_DATE", 
"FORM_TAX_PRD", 
"TYPE_PLAN_ENTITY_CD", 
"FINAL_FILING_IND", 
"PLAN_NAME",
"SPONS_DFE_PN",
"PLAN_EFF_DATE",
"SPONS_DFE_EIN",
"ADMIN_EIN",
"TOT_PARTCP_BOY_CNT",
"TOT_ACTIVE_PARTCP_CNT",
"RTD_SEP_PARTCP_RCVG_CNT",
"RTD_SEP_PARTCP_FUT_CNT",
"SUBTL_ACT_RTD_SEP_CNT",
"BENEF_RCVG_BNFT_CNT",
"TOT_ACT_RTD_SEP_BENEF_CNT",
"PARTCP_ACCOUNT_BAL_CNT",
"SEP_PARTCP_PARTL_VSTD_CNT",
"CONTRIB_EMPLRS_CNT",
"TYPE_PENSION_BNFT_CODE",
"TYPE_WELFARE_BNFT_CODE",
"FUNDING_INSURANCE_IND",
"FUNDING_SEC412_IND",
"FUNDING_TRUST_IND",
"FUNDING_GEN_ASSET_IND",
"BENEFIT_INSURANCE_IND",
"BENEFIT_SEC412_IND",
"BENEFIT_TRUST_IND",
"BENEFIT_GEN_ASSET_IND",
"SCH_R_ATTACHED_IND",
"SCH_MB_ATTACHED_IND",
"SCH_SB_ATTACHED_IND",
"SCH_H_ATTACHED_IND",
"SCH_I_ATTACHED_IND",
"SCH_A_ATTACHED_IND",
"NUM_SCH_A_ATTACHED_CNT",
"SCH_C_ATTACHED_IND",
"SCH_D_ATTACHED_IND",
"SCH_G_ATTACHED_IND",
"FILING_STATUS",
"DATE_RECEIVED"
)
form5500_min <- form5500[,(names(form5500) %in% keeps)]

write.csv(x=form5500_min, file="../Data/f_5500_2013_latest-min.csv")
}

# Filter for 401K plans only
f5500_401k <- form5500[grep("401", form5500$PLAN_NAME),]

# Merge 5500 401K and 5500R data
f5500_merge <- merge(f5500_401k, form5500R, by=c("ACK_ID"))
```


# Explore Data

```{r}
summary(ssa_benefit)
summary(ssa_taxamt)
summary(ssa_taxrate)

summary(f5500_401k)
summary(f5500_merge)
```

## Graphs

```{r , fig.height=75}
plot(ssa_taxamt$Year, ssa_taxamt$Employee..OASI.)

bp <- ggplot(ssa_benefit, aes(x=Monthly.Benefit..dollars., y=Total.Number)) + geom_point()
bp <- bp + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
bp

```

# Analysis

```{r}


```

## Graphs

```{r , fig.height=75}

```

# Comments

* 

# TODO

* Start basic work for each section of this project.